baseURL: https://elephantintheroom.dev/
languageCode: en-us
title: Elephant In The Room
theme: poison
paginate: 10
taxonomies:
  series: 'series'
  tags: 'tags'
params:
  brand: Elephant In The Room
  brand_image: https://mwtaylor.github.io/ElephantLogos/elephant_itr400.png
  favicon: https://mwtaylor.github.io/ElephantLogos/elephant_itr100.png
  menu:
    - Name: "About"
      URL: "/about/"
      HasChildren: false
    - Name: "Posts"
      URL: "/posts/"
      Pre: "Recent"
      HasChildren: true
      Limit: 5
  github_url: "https://github.com/mwtaylor/DevelopmentBlog"
  mastodon_url: "https://mwtaylor.social/@Michael"
