baseURL: https://elephantintheroom.dev/
languageCode: en-us
title: Elephant In The Room
theme: poison
paginate: 10
taxonomies:
  series: 'series'
  tags: 'tags'
params:
  brand: Elephant In The Room
  menu:
    - Name: "About"
      URL: "/about/"
      HasChildren: false
    - Name: "Posts"
      URL: "/posts/"
      Pre: "Recent"
      HasChildren: true
      Limit: 5
  github_url: "https://github.com/mwtaylor/DevelopmentBlog"
  mastodon_url: "https://mwtaylor.social/@Michael"
